spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${COGNITO_CLIENT_ID}
            client-secret: ${COGNITO_CLIENT_SECRET}
        provider:
          cognito:
            issuer-uri: https://cognito-idp.af-south-1.amazonaws.com/af-south-1_KTd5Q14k0