name: CI/CD

on:
  push:
      branches: [ main ]

permissions:
  contents: read
  id-token: write

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4