name: CI/CD

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

env:
  terraform_directory: './terraform'

jobs:
  prod-ci:
    name: "Prod CI"
    uses: ./.github/workflows/prod-ci.yaml

  terraform-apply:
    name: "Terraform apply"
    needs: prod-ci
    uses: ./.github/workflows/terraform-cd.yaml

  database-migration:
    name: "Liquibase update"
    uses: ./.github/workflows/liquibase-cd.yaml
