name: Production CI

on:
  workflow_call: 
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]

permissions:
  contents: read
  id-token: write

env:
  terraform_directory: './terraform'

jobs:
  terraform-checks:
    name: "Terraform checks"
    uses: ./.github/workflows/terraform-checks.yaml
  
  terraform-plan:
    name: "Terraform plan"
    runs-on: ubuntu-latest
    needs: terraform-checks
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: ${{secrets.AWS_ASSUME_ROLE}}
          aws-region: "eu-west-1"

      - name: Terraform Init
        working-directory: ${{env.terraform_directory}}
        id: init
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{env.terraform_directory}}
        id: plan
        run: terraform plan
