name: CI

on:
  workflow_call:
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  contents: read
  id-token: write

env:
  terraform_directory: './terraform'

jobs:
  terraform-checks:
    name: "Terraform checks"
    uses: ./.github/workflows/terraform-checks.yaml
  
  terraform-plan:
    name: "Terraform plan"
    needs: terraform-checks
    secrets: inherit
    uses: ./.github/workflows/terraform-ci.yaml

  test-database-migration:
    name: "Liquibase checks"
    secrets: inherit
    uses: ./.github/workflows/liquibase-ci.yaml

  app-ci:
    name: "Application checks"
    secrets: inherit
    uses: ./.github/workflows/app-ci.yaml